config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :quotes
  end

  resources :quotes
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  has_one :quote

  scope :quotes, -> {where(is_quote?: true)}

  def is_quote?
    !self.quote.nil?
  end
end

app/models/spree/quote.rb
class Spree::Quote < ActiveRecord::Base
  belongs_to :order

  before_create :set_expiration_date

  validate :order_items, :on => :create
  validate :order_addresses, :on => :create

  def set_expiration_date
    self.expiration_date = DateTime.now + Spree::Config[:default_expiration_period].to_i.days
  end

  def order_items
    errors_msg = []
    errors_msg = Spree.t('errors.line_items') unless order.line_items.size > 0
    errors.add :order, errors_msg unless errors_msg.empty?
  end

  def order_addresses
    errors_msg = []
    errors_msg << Spree.t('errors.ship_address') if order.shipping_address.nil?
    errors_msg << Spree.t('errors.bill_address') if order.billing_address.nil?
    errors.add :order, errors_msg.join("<br/><br/>") unless errors_msg.empty?
  end

  def state
    (expiration_date - DateTime.now) > Spree::Config[:default_expiration_period]
  end

end

app/controllers/spree/admin/quotes_controller.rb
module Spree
  module Admin
    class QuotesController < BaseController
      before_action :load_quote, only: [:edit, :update]
      respond_to :pdf

      def index
        @quotes = Quote.all
      end

      def show
        load_order
        render layout: false , template: "spree/admin/orders/quote.pdf.prawn"
      end

      def create
        @quote = Quote.find_or_create_by(quote_params)
        if @quote.valid?
          flash[:success] = Spree.t('quote_created')
          redirect_to edit_admin_order_path(@quote.order)
        else
          flash[:error] = @quote.errors.messages.values.join(", ")
          redirect_to :back
        end
      end

      def edit; end

      def update
        if @quote.update_attributes(quote_params)
          flash[:success] = Spree.t('quote_updated')
          redirect_to edit_admin_quote_path(@quote)
        else
          flash[:error] = @quote.errors.messages.values.join(", ")
          render action: :edit
        end
      end

      private

      def quote_params
        params[:quote].permit(:order_id, :payment_received)
      end

      def load_order
        @order = Quote.find(params[:id]).try(:order)
        authorize! action, @order
      end

      def load_quote
        @quote = Quote.find(params[:id])
      end

    end
  end
end

app/controllers/spree/quotes_controller.rb
module Spree
  class QuotesController < Spree::StoreController
    respond_to :pdf

    before_action :set_bill_address, only: :create

    def show
      load_order
      render :layout => false, :template => "spree/admin/orders/quote.pdf.prawn"
    end

    def create
      @quote = Quote.find_by(quote_params) || Quote.create(quote_params)
      if @quote.valid? && @order.bill_address.present?
        render json: @quote.to_json, status: 200
      else
        @quote.errors.add(:bill_address, Spree.t('errors.bill_address')) if @order.bill_address.nil?
        render json: @quote.errors.messages.values.join(", "), status: 422
      end
    end

    private

    def quote_params
      params[:quote].permit(:order_id, :payment_received)
    end

    def address_params
      params[:quote].permit(
        :use_shipping_address,
        :bill_address_attributes => permitted_address_attributes)
    end

    def load_order
      @order = Quote.find(params[:id]).try(:order)
    end

    def set_bill_address
      @order.bill_address = spree_current_user.default_bill_address
      if @order.bill_address.blank?
        if address_params[:use_shipping_address] == 'false'
          @order.build_bill_address(address_params[:bill_address_attributes])
        else
          @order.clone_shipping_address
        end
      end

      @order.save
      @order.reload
    end

  end
end

app/helpers/spree/admin/quotes_helper.rb
module Spree
  module Admin
    module QuotesHelper

      def status_text state
        state == true ? 'available' : 'expired'
      end

      def quote_payment_state payment_state
        payment_state.blank? ? 'no paid' : 'paid'
      end

    end
  end
end

app/views/spree/admin/quotes/_form.html.erb
<div data-hook="admin_quote_form_fields">
  <div class="field checkbox align-center">
    <label>
      <%= f.check_box :payment_received, { checked: @quote.payment_received }, '1', '0' %>
      <%= Spree.t(:payment_received) %>
    </label>
  </div>
  <div class="clear"></div>
</div>

app/views/spree/admin/quotes/_quotes.html.erb
<% if quotes.try(:any?) %>
  <table class="index responsive" id="listing_quote_orders" data-hook>
    <colgroup>
      <col style="width: 20%;">
      <col style="width: 20%;">
      <col style="width: 20%;">
      <col style="width: 20%;">
      <col style="width: 20%;">
    </colgroup>
    <thead>
    <tr data-hook="admin_orders_index_headers">
      <th>Created at</th>
      <th>Order</th>
      <th>Expires at</th>
      <th>State</th>
      <th class="quotes-actions actions" data-hook="admin_quote_index_header_actions"></th>
    </tr>
    </thead>
    <tbody>
    <% quotes.each do |quote| %>
        <tr data-hook="admin_orders_index_rows" class="<%= cycle('odd', 'even') %>">
          <td class="align-center"><%= l quote.created_at.to_date %></td>
          <td class="align-center"><%= link_to quote.order.number, edit_admin_order_path(quote.order.number) %></td>
          <td class="align-center"><%= l quote.expiration_date.to_date %></td>
          <td class="align-center">
            <span class="state <%= status_text(quote.state) %>"><%= Spree.t("#{status_text(quote.state)}") %></span></td>
          </td>
          <td class="quote-actions actions" data-hook="admin_quote_index_row_actions">
            <%= link_to '', edit_admin_quote_path(quote), no_text: true, class: 'icon_link icon-edit no-text with-tip' %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/quotes/_resource_links.html.erb
<div class="form-buttons" data-hook="buttons">
  <%= button Spree.t('actions.update'), 'icon-refresh' %>
</div>

app/views/spree/admin/quotes/edit.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:quotes) %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:admin, Spree::Order) %>
    <li><%= button_link_to Spree.t(:generate_pdf), admin_quote_path(@quote), :icon => 'icon-file' %></li>
    <li><%= button_link_to Spree.t(:back_to_quote_list), admin_quotes_path, :icon => 'icon-arrow-left' %></li>
  <% end %>
<% end %>

<%= form_for [:admin, @quote], method: :put, html: { :multipart => true } do |f| %>
  <fieldset class="no-border">
    <%= render partial: 'form', :locals => { :f => f } %>
    <%= render partial: 'resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/quotes/index.html.erb
<% content_for :page_title do %>
    <%= "Listing Quotes" %>
<% end %>
<% content_for :page_actions do %>
    <% if can?(:admin, Spree::Order) %>
        <li><%= button_link_to Spree.t(:back_to_orders_list), admin_orders_path, :icon => 'icon-arrow-left' %></li>
    <% end %>
<% end %>

<div data-hook="admin_quote_edit_header">
  <%= render partial: 'spree/shared/error_messages', locals: { target: @quote } %>
</div>

<%= render partial: 'quotes', locals: { quotes: @quotes } %>

app/views/spree/admin/shared/_order_tabs.html.erb
<% content_for :page_title do %>
  <% if @order.quote.present? && @order.payment? %>
    <%= link_to "#{Spree.t(:order)} ##{@order.number} - Quote", spree.edit_admin_order_path(@order) %>
  <% else %>
    <%= link_to "#{Spree.t(:order)} ##{@order.number}", spree.edit_admin_order_path(@order) %>
  <% end %>
<% end %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:order_information) %>
<% end %>

<% content_for :sidebar do %>
  <%= render "spree/admin/shared/order_summary", checkout_steps: @order.checkout_steps %>
  <%= render "spree/admin/shared/order_submenu", current: current, checkout_steps: @order.checkout_steps %>
<% end %>